version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/opt/code
        depends_on:
            - postgres
    postgres:
        image: postgres:9.4-alpine
