"""empty message

Revision ID: 5ea045647489
Revises: 1ec98fe1dbf5
Create Date: 2017-06-11 14:59:22.510000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea045647489'
down_revision = '1ec98fe1dbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('args', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'args')
    # ### end Alembic commands ###
