"""empty message

Revision ID: 720cda789bc6
Revises: 
Create Date: 2017-06-08 14:40:20.600000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720cda789bc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.Column('submission_result', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question'], [u'questions.id'], ),
    sa.ForeignKeyConstraint(['user'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('celery_tasksetmeta',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('taskset_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=u'celery_tasksetmeta_pkey'),
    # sa.UniqueConstraint('taskset_id', name=u'celery_tasksetmeta_taskset_id_key')
    # )
    # op.create_table('celery_taskmeta',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=u'celery_taskmeta_pkey'),
    # sa.UniqueConstraint('task_id', name=u'celery_taskmeta_task_id_key')
    # )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
